:sparkles: feat: search token per type
interest-protocol/interest-dex-interface pull request #36
Opened 2024-11-15 13:57 UTC by atilasousa

2024-11-16 19:02 UTC, MarioBatalha approved these changes

2024-11-17 20:36 UTC, KipandaJr requested changes
- When search by type and select the coin, i can't see this coin on the input
- check the conflits with develop

2024-11-18 18:42 UTC, MarioBatalha approved these changes

2024-11-18 18:54 UTC, KipandaJr approved these changes

2024-11-18 22:12 UTC, merged