:sparkles: feat: adding execution time in swap
interest-protocol/interest-dex-interface pull request #51
Opened 2024-11-20 18:21 UTC by atilasousa

2024-11-23 20:46 UTC, MarioBatalha approved these changes

2024-11-23 20:55 UTC, KipandaJr reviewed
![image](https://github.com/user-attachments/assets/8fa57a85-4abb-4d45-9cd2-572d85f1b2b3)

2024-11-24 10:22 UTC, KipandaJr requested changes
![image](https://github.com/user-attachments/assets/b7e2c522-4335-445e-934f-4fc601416e59)
same error in both wallet

2024-11-25 18:44 UTC, KipandaJr approved these changes

2024-11-25 19:27 UTC, merged