:bug: Fix find pools
interest-protocol/interest-dex-interface pull request #86
Opened 2024-12-03 01:23 UTC by MarioBatalha

2024-12-03 01:23 UTC, git-marcopitra commented
Task linked: [CU-8696tr6nr Find pool not working](https://app.clickup.com/t/8696tr6nr)

2024-12-03 18:20 UTC, KipandaJr requested changes
Fix the conflits and the Find dosent work on My Position

2024-12-07 17:29 UTC, KipandaJr approved these changes

2024-12-07 18:22 UTC, atilasousa approved these changes

2024-12-10 09:38 UTC, git-marcopitra approved these changes

2024-12-10 09:39 UTC, merged